# Generated by Django 3.2 on 2022-05-06 10:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('messages', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('catagory', models.CharField(default='Machine_one', max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('rent_price', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='equipments')),
                ('image_2', models.ImageField(upload_to='equipments')),
                ('Description', models.TextField()),
                ('availability', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Human_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=500)),
                ('helpertype', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField()),
                ('img', models.ImageField(default='default_hr.jpg', upload_to='hr/')),
                ('experience', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durations', models.CharField(choices=[('1', '1-Day'), ('2', '2-Day'), ('3', '3-Day'), ('4', '4-Day'), ('5', '5-Day'), ('6', '6-Day'), ('7', '7-Day'), ('8', '8-Day'), ('9', '9-Day'), ('10', '10-Day')], max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6)),
                ('age', models.CharField(choices=[('grp0', ' new born babies < 12 months'), ('grp1', '1 to 10 yrs'), ('grp2', '11 to 20 yrs'), ('grp3', '21 to 30 yrs'), ('grp4', '31 to 40 yrs'), ('grp5', '41 to 60 yrs'), ('grp6', '60+')], default='', max_length=30)),
                ('request_for', models.TextField(default='')),
                ('service_is_complete', models.BooleanField(default='True')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_person', to='app.human_resource')),
            ],
            options={
                'verbose_name': 'Patient detail',
                'verbose_name_plural': 'Patient details',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackfor', models.CharField(choices=[('CMP', 'complain'), ('REV', 'review')], default='REV', max_length=15)),
                ('message', models.CharField(max_length=100)),
                ('rating', models.IntegerField(help_text='give a rating between 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('is_payment_complete', models.BooleanField()),
                ('date_purchase', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(default='default_pc.jpg', upload_to='pc/')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered''''[['[]]] in the format: '999999999'. Up to 15 digits allowed.", regex='^\\d{10,15}$')])),
                ('pic', models.ImageField(upload_to='users')),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(default='not available')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Processing'), ('T', 'In Transit'), ('D', 'delivered'), ('C', 'cancelled')], default='P', max_length=15)),
                ('date', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.equipment')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_price', models.IntegerField(null=True)),
                ('rent_date', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField(auto_now=True)),
                ('Delivery_Address', models.TextField(max_length=500)),
                ('is_date_expired', models.BooleanField(default=True)),
                ('Fine', models.IntegerField(null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
