# Generated by Django 3.2 on 2021-06-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=500)),
                ('helpertype', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='HumanResource',
        ),
    ]
