# Generated by Django 3.2 on 2021-06-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_purchase_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='img',
            field=models.ImageField(default='default_pc.jpg', upload_to='pc/'),
        ),
    ]
