# Generated by Django 3.2 on 2021-06-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='age',
            field=models.CharField(choices=[('Teenager', '21 to 32'), ('Elder', '31 to 44')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_for',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='durations',
            field=models.CharField(choices=[('1', '1-Day'), ('2', '2-Day'), ('3', '3-Day'), ('4', '4-Day'), ('5', '5-Day'), ('6', '6-Day'), ('7', '7-Day'), ('8', '8-Day'), ('9', '9-Day'), ('10', '10-Day')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_person', to='app.human_resource'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_is_complete',
            field=models.BooleanField(default='True'),
        ),
    ]
