# Generated by Django 3.2 on 2021-07-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='image_1',
            new_name='image',
        ),
    ]
