# Generated by Django 3.2 on 2021-07-08 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rating',
            field=models.IntegerField(help_text='give a rating between 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
