# Generated by Django 3.2 on 2021-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_report_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='human_resource',
            name='experience',
            field=models.IntegerField(default=1),
        ),
    ]
