# Generated by Django 3.2.5 on 2021-08-01 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_human_resource_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'verbose_name': 'Patient detail', 'verbose_name_plural': 'Patient details'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered''''[['[]]] in the format: '999999999'. Up to 15 digits allowed.", regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='age',
            field=models.CharField(choices=[('grp0', ' new born babies < 12 months'), ('grp1', '1 to 10 yrs'), ('grp2', '11 to 20 yrs'), ('grp3', '21 to 30 yrs'), ('grp4', '31 to 40 yrs'), ('grp5', '41 to 60 yrs'), ('grp6', '60+')], default='', max_length=30),
        ),
    ]
